### ISSUE TITLE
Firefox 6.0 the selecting multiply messages and deleting doesn't work 

### ISSUE THREAD

**Issue by ghost** [jcutler/Missing-E#25]
It tells me that i need to try again later, and it is version 2.0.2

**Comment by jcutler** [comment]
This is an indication of a connection problem to Tumblr or Tumblr's servers not responding correctly. **Missing e** is most likely working correctly.

**Comment by ghost** [comment]
actually it is giving me a 403 forbidden when run thru firebug's javascript console when using tumblr.com/delete_posts and that is what missing e is using to delete it but in actually when you use the tumblr X it goes thru to http://www.tumblr.com/deny_submission/9278531559 or http://www.tumblr.com/deny_submission/{post_id} ![screen_shot](http://i.imgur.com/YUwrf.png)

**Comment by jcutler** [comment]
A forbidden error makes no sense. Are you logged in? There is only one other possibility....

In order to delete multiple posts, Missing e does an AJAX call to delete_posts. That is expected. Due to the limitations of that page, privately-answered message and asks for each account are deleted separately.

For example, if I select three messages: one ask submitted to cutlerish, one ask submitted to missing-e and one privately-answered ask that came back to me, then three calls to delete_posts are made.

I don't think I tested it with submissions, though.

Perhaps you can try deleting one at a time (one of each type would suffice) using the "Delete Selected" button and let me know which work and which don't.

**Comment by jcutler** [comment]
I just tested with submitted posts, and that works fine for me.

**Comment by jcutler** [comment]
Hmm... before you do that, let me know if any of them are submitted posts. Perhaps it fails trying to delete submitted posts together with asks...

**Comment by ghost** [comment]
I wasn't deleting a submission i was deleting an ask

**Comment by jcutler** [comment]
Okay, well I can't repeat it. Every combination of deleting works fine for me. Can you find some minimal combination of selected posts that won't delete successfully (after confirming that you can delete single posts using the delete selected button).

**Comment by jcutler** [comment]
I have not received a response regarding this. Because I cannot repeat, I am closing this issue. If you are able to provide the information, please reopen!
