### ISSUE TITLE
Misalignment on dashboard

### ISSUE THREAD

**Issue by Heliosmaster** [jcutler/Missing-E#27]
This is a screenshot of the problem: 

http://cl.ly/2p3T2j1X3o3f3n2P403Y

Zooming in alignes everything. But when new post are loaded, the newly loaded are again misaligned and zooming out fixes that. Rinse and repeat :)

Using chrome: 17.0.928.0 dev-m
Latest version of missing-E

**Comment by jcutler** [comment]
This is a problem with Chrome's dev channel. In fact, if you disable Missinge e, you'll still find the misalignment in the post buttons. I'll keep my eye on it, though.

**Comment by Heliosmaster** [comment]
What misalignment are you referring to? I disabled Missing E and this is the result: http://cl.ly/0c19202P3f0Q2C3H0d0Q

Also in the post windows, no other problem. (same behaviour in canary)

**Comment by jcutler** [comment]
So, I do remember seeing this when I installed the dev channel, but I didn't want to install it again (I can't run it standalone with the stable channel).

However, I am now running Missing e on 17.0.940.0 canary and I do not see the problem.

Do you have this problem on canary? Or is it just dev? Also, what OS are you using?

If you find it is happening in the latest version of dev, but NOT in canary, then chances are an update for the dev channel will fix it soon.

If you find it is happening in canary also, then I'll have to look into it (it'll be a bit of a challenge since I cannot repeat it).

**Comment by Heliosmaster** [comment]
Well.. I don't know what to say. Probably I am a fool, but now it works :| I probably got mixed up between canary and dev (using them at the same time)... got to learn to check thrice before talking.

Sorry about this inconvenience, at least I am glad to know that you listen to feedback :D

**Comment by jcutler** [comment]
No, I'm pretty sure you had it right. I did see it before in the dev channel. Most likely it is a problem that got fixed fairly recently (in the last week or so) in the Chrome source code.

**Comment by Heliosmaster** [comment]
As soon as you replied to me, one week ago, I looked in canary and the problem was also there, and tonight i also checked but i got mixed up and thought it was still broken ;) now only dev it is, so let's wait for the upgrade. I could not use tumblr w/o missingE :P (i use dev all the time, only some testing is done on canary ;) )
