### ISSUE TITLE
"To Dash" button doesn't always work.

### ISSUE THREAD

**Issue by jackholt** [jcutler/Missing-E#3]
Using v1.0.19. 
Some blogs work as expected (redcloud, thatguyles, milkglassmao)
Some do not (bestgirlbetty, steelopus)
Failure mode: Clicking the "<-Dash" button takes me to a random post by a random user. (Deterministically, though. If I do it twice in a row, it goes to the same post each time. But a different post for steelopus than bestgirlbetty.) Not sure what they have in common. I used the most recent post of each user:
http://www.steelopus.com/post/3660689607/laser-etching-lenovo-x201s-via-steelopus-heres
http://bestgirlbetty.tumblr.com/post/3649816704/i-know-some-parents-are-assholes-but-at-the

**Comment by jcutler** [comment]
I've noticed this happening also. I've also seen that sometimes it works fairly soon after, but then exhibits this issue after a while and from then on.

I have no idea what the issue is, and suspect a tumblr problem. Those posts also no longer show up in the feed if you just scroll back to them.

This is also a problem for bookmarker, since it uses the same technique to jump directly back to a post.

I'll look into it, but there may be no solution until Tumblr fixes the problem.
